/* 如果库不存在才创建库 */
CREATE DATABASE IF NOT EXISTS test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

/* 使用库 */
USE test;

/* 先删除表，再创建表 */
DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST
(
    USER_ID     INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'userId',
    USER_NAME   VARCHAR(255) DEFAULT '' COMMENT 'userName',
    CREATE_TIME DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime'
);

/* 测试数据 */
INSERT INTO TEST (USER_NAME, CREATE_TIME)
VALUES ('张三', CURRENT_TIMESTAMP);
INSERT INTO TEST (USER_NAME, CREATE_TIME)
VALUES ('李四', CURRENT_TIMESTAMP);
INSERT INTO TEST (USER_NAME, CREATE_TIME)
VALUES ('王五', CURRENT_TIMESTAMP);